# Kopiert ein VST3-Bundle nach DEST. Eine vorhandene Dubgefahren.config.json im Ziel bleibt unangetastet.
# Aufruf: cmake -DBUNDLE=<pfad/Dubgefahren.vst3> -DDEST=<zielordner> -P InstallBundle.cmake
cmake_minimum_required(VERSION 3.25)
if(NOT IS_DIRECTORY "${BUNDLE}")
    message(FATAL_ERROR "Bundle nicht gefunden: ${BUNDLE}")
endif()
get_filename_component(name "${BUNDLE}" NAME)
set(target "${DEST}/${name}")
file(GLOB_RECURSE files RELATIVE "${BUNDLE}" "${BUNDLE}/*")
foreach(f IN LISTS files)
    if(f MATCHES "Dubgefahren\\.config\\.json$" AND EXISTS "${target}/${f}")
        message(STATUS "Config vorhanden, nicht überschrieben: ${target}/${f}")
        continue()
    endif()
    get_filename_component(dir "${target}/${f}" DIRECTORY)
    file(MAKE_DIRECTORY "${dir}")
    file(COPY_FILE "${BUNDLE}/${f}" "${target}/${f}")
    message(STATUS "Installiert: ${target}/${f}")
endforeach()
